import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/myUi/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[#ebf0fb] `}>
				<div className="flex lg:flex-row flex-col sticky top-0">
					<SideBar />
					<div className="mx-auto container p-5">{children}</div>
				</div>
			</body>
		</html>
	);
}
